name: lint

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  lint:
    name: flutter analyze
    runs-on: ubuntu-latest
    steps:
      - name: set up repository
        uses: actions/checkout@v4
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: flutter pub get
        run: flutter pub get
      - name: flutter analyze
        run: flutter analyze